<script>
  import { onMount } from "svelte";

  let showModal = false;
  const storageKey = "fireInSiteDisclaimerAcknowledged";

  onMount(() => {
    const acknowledged = localStorage.getItem(storageKey);
    if (!acknowledged) {
      showModal = true;
    }
  });

  function closeModal() {
    localStorage.setItem(storageKey, "true");
    showModal = false;
  }
</script>

{#if showModal}
  <div
    class="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50"
  >
    <div class="bg-white rounded-2xl shadow-lg max-w-xl w-full p-6">
      <h2 class="text-xl font-semibold text-red-700 mb-4">
        🔥 FireInSite Disclaimer
      </h2>
      <p class="mb-3 text-sm text-gray-700">
        <strong>Important Notice:</strong> FireInSite is an experimental fire behaviour
        prediction tool currently under active development. While we have made every
        effort to ensure the accuracy and reliability of the predictions provided,
        the underlying models and data are subject to ongoing improvement and validation.
      </p>
      <p class="mb-3 text-sm text-gray-700">
        Fire behaviour is influenced by many complex and dynamic factors, and as
        such, the predictions generated by FireInSite should be considered <strong
          >advisory only</strong
        >. Users are strongly encouraged to apply their own judgment and consult
        additional sources when making decisions based on this application.
      </p>
      <p class="mb-4 text-sm text-gray-700">
        <strong
          >The authors and developers of FireInSite cannot accept responsibility
          or liability for any loss, damage, or consequences resulting from the
          use of this application or the information it provides.</strong
        >
      </p>
      <div class="flex justify-end">
        <button
          on:click={closeModal}
          class="bg-red-600 hover:bg-red-700 text-white font-medium py-2 px-4 rounded-lg transition"
        >
          I Understand
        </button>
      </div>
    </div>
  </div>
{/if}
